---
- name: Init config
  hosts: all
  gather_facts: false

  vars_files: [vars.yml]

  vars:
    assets_path: '{{ playbook_dir }}/assets'
    files_path: '{{ playbook_dir }}/files'
    handlers_path: '{{ playbook_dir }}/handlers'
    tasks_path: '{{ playbook_dir }}/tasks'
    templates_path: '{{ playbook_dir }}/templates'

  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || apt update && apt install -y python3-minimal
      changed_when: false
      become: true

    - name: Network config
      include_tasks: '{{ tasks_path }}/network.yml'
      tags: network

    - name: Base config
      include_tasks: '{{ tasks_path }}/base.yml'
      tags: base

    - name: SSH config
      include_tasks: '{{ tasks_path }}/ssh.yml'
      tags: ssh

  handlers:
    - name: Restart SSH
      include_tasks: '{{ handlers_path }}/ssh.yml'
      tags: base

    - name: Restart qemu-ga
      include_tasks: '{{ handlers_path }}/qemu_ga.yml'
      tags: base
