---
- name: Base config
  block:
    - name: Install sudo
      apt:
        name: sudo
        state: latest
        update_cache: true
      become: true

    - name: Create the user
      user:
        name: '{{ USERNAME }}'
        password: "{{ PASSWORD | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
      become: true

    - name: Set passwordless sudo
      community.general.sudoers:
        name: users
        state: present
        user: '{{ USERNAME }}'
        commands: ALL
      become: true

    - name: Insall qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: latest
        update_cache: true
      notify: Restart qemu-ga
      become: true
      when: INSTALL_QEMU_GA

  tags: base
