---
- name: Network configuration
  block:
    - name: Disable ipv6
      sysctl:
        name: '{{ ipv6_kernel_parameter }}'
        value: '1'
        sysctl_file: /etc/sysctl.d/disable-ipv6.conf
        reload: true
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
      loop_control:
        loop_var: ipv6_kernel_parameter
      become: true
