---
- name: Configure SSH
  block:
    - name: Ensure the .ssh directory exists
      file:
        path: /home/{{ USERNAME }}/.ssh
        state: directory
        owner: '{{ USERNAME }}'
        group: '{{ USERNAME }}'
        mode: '0700'

    - name: Set ssh key on hosts
      authorized_key:
        user: '{{ USERNAME }}'
        state: present
        key: "{{ lookup('file', SSH_KEY_PATH) }}"

    - name: Remove default values in sshd_config
      replace:
        path: /etc/ssh/sshd_config
        regexp: ^\s*({{ item }}.*)
        replace: '# \1'
      with_items:
        - Port
        - PermitRootLogin
        - MaxAuthTries
        - MaxSessions
        - PasswordAuthentication
        - PermitEmptyPasswords
        - X11Forwarding
        - AuthorizedKeysFile
      become: true

    - name: Apply sshd config
      template:
        src: 01_ssh.j2
        dest: /etc/ssh/sshd_config.d/01_ssh.conf
        mode: '0600'
      notify: Restart SSH
      become: true

  tags: ssh
